### ISSUE TITLE
Do we need to import Tuple/List etc from typing?

### ISSUE THREAD

**Issue by GrahamCampbell** [arachnys/protostub#6]

**Comment by ghost** [comment]
We do indeed. Seems like MyPy can handle some things anyway (for instance, if you don't import Any it still picks it up fine), however it would be correct to ensure imports are there.

**Comment by GrahamCampbell** [comment]
I guess we technically should make sure there are no collisions with names from the protobuf files too.

**Comment by ghost** [comment]
We could just leave it as `import typing`, and then use the package name too. I'm not certain how well that would work though.
