### ISSUE TITLE
How to build for windows?

### ISSUE THREAD

**Issue by GrahamCampbell** [arachnys/protostub#8]

**Comment by MrSaints** [comment]
Ideally this will be resolved in tandem with https://github.com/arachnys/protostub/issues/1. Windows is a target in `goreleaser`. That, and you could just use Docker ;)

**Comment by GrahamCampbell** [comment]
That docker command won't use my fork though?

**Comment by MrSaints** [comment]
If you are using Docker @GrahamCampbell, you can override the remote image with your own locally built version:

```
docker build -t arachnysdocker/protostub .
# docker run ...
```

**Comment by GrahamCampbell** [comment]
Getting the error "unable to find image locally"

**Comment by hazzadous** [comment]
so you'll have to run something like `docker build -t someidentifier .` then use that in place of arachnysdocker/protostub

**Comment by GrahamCampbell** [comment]
`docker build -t protostub:latest .` worked, but now I get "invalid mode: /protostub"
